spring.application.name=com.gregory.vehicleRentalAPI

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

admin.default.username=${ADMIN_USERNAME}
admin.default.email=${ADMIN_EMAIL}
admin.default.password=${ADMIN_PASSWORD}
